#!/bin/bash

cd $SNAP_DATA
[[ -f switch-web.ok ]] && exit 0

[[ -d www ]] && mv www wwwold && mkdir www && git clone https://github.com/skidoomanubuntu/demowrapper.git www

cd $SNAP_DATA/www
git remote add upstream https://github.com/skidoomanubuntu/demowrapper.git
git fetch upstream
git checkout main
git rebase upstream/main
git config pull.rebase true
git pull
git pull -f
git reset --hard upstream/main
git pull
touch ../switch-web.ok

exit 0
