name: iotdevice-lighttpd # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A simple IOT Demo web server for wrapper
description: |
        This is a simple web server with lighttpd debian package from Ubuntu archive
        The webpage content can be replaced by replacing files under /var/snap/lighttpd-snap/current/www/
        Current lighttpd service is running with lighttpd.conf in /var/snap/lighttpd-snap/current/lighttpd.conf
        
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  iotdevice-lighttpd:
    command: lighttpd-wrapper.sh
    daemon: simple
    plugs: [network, network-bind]


parts:
  iotdevice-lighttpd:
    plugin: nil
    stage-packages:
            - lighttpd

  common:
    plugin: dump
    source: .
    override-prime: |
      snapcraftctl prime
      sed -i "s/lighttpd-snap/$SNAPCRAFT_PROJECT_NAME/" $SNAPCRAFT_PRIME/lighttpd.conf

  demowrapper:
    plugin: dump
    source: https://github.com/skidoomanubuntu/demowrapper.git
    override-build: |
      TARGET=$SNAPCRAFT_PART_INSTALL/www
      mkdir -p $TARGET
      cp -vr * $TARGET
