name: iotdevice-lighttpd # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: "0.3" # change to 0.2 as snapd-control auto-connect is granted
summary: A simple IOT Demo web server for wrapper
description: |
  Reboot of the lighttpd snap with a few tidbits for IOT Demos by FE
  Version 0.3 adds robustness in check-video
  Version 0.2 adds snapd-control auto-connect
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  iotdevice-lighttpd:
    command: run-lighttpd
    daemon: simple
    plugs: [network, network-bind]
  php-fpm:
    command: run-php-fpm
    daemon: simple
    plugs: [network, network-bind]
  check-video:
    command: check-video
    daemon: oneshot
    plugs: [network, network-bind]
  check-web:
    command: check-web
    daemon: oneshot
    plugs: [network, network-bind]
    environment:
      PATH: $PATH:$SNAP/usr/lib/git-core
  snap-list:
    command: snap-list
    daemon: oneshot
    plugs: [network, network-bind, snapd-control]

architectures:
  - build-on: arm64
  - build-on: amd64

parts:
  iotdevice-lighttpd:
    plugin: nil
    stage-packages:
      - lighttpd
      - spawn-fcgi
      - php
      - php-cgi
      - php-fpm
    override-prime: |
      craftctl default
      #      rm $CRAFT_PRIME/usr/bin/php-cgi
      cp -vf $CRAFT_PRIME/usr/bin/php-cgi.default $CRAFT_PRIME/usr/bin/php-cgi
  check-web:
    plugin: nil
    stage-packages:
      - git
      - curl
    source: .
    override-build: |
      cp -av check-web $CRAFT_PART_INSTALL
      TARGET=$SNAPCRAFT_PART_INSTALL/www
      mkdir -p $TARGET
      git clone https://github.com/jicheu/demowrapper.git $TARGET
  check-video:
    plugin: nil
    source: .
    stage-packages:
      - wget
    override-build: |
      cp -av check-video $CRAFT_PART_INSTALL
    after: [check-web]
  snap-list:
    plugin: nil
    source: .
    stage-packages:
      - jq
    override-build: |
      cp -av snap-list $CRAFT_PART_INSTALL
    after: [check-video]
  copy:
    plugin: nil
    source: .
    override-build: |
      cp -av run-lighttpd $CRAFT_PART_INSTALL
      cp -av run-php-fpm $CRAFT_PART_INSTALL
    after: [iotdevice-lighttpd]
